congo/checkout/models.py
from congo.database import PkModel, reference_col, relationship


class Checkout(PkModel):
    __tablename__ = "checkout"
    cart_id = reference_col("carts", nullable=True)
    carts = relationship("Cart", backref="checkouts")

    book_id = reference_col("book", nullable=True)
    book = relationship("Book", backref="checkouts")

    def __repr__(self):
        return f"<Checkout(id:{self.id}, user_id:{self.cart_id}, book_id:{self.book_id}>"

congo/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from congo.database import Column, PkModel, db, reference_col, relationship
from congo.extensions import bcrypt


class Role(PkModel):
    """A role for a user."""

    __tablename__ = "roles"
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col("users", nullable=True)
    user = relationship("User", backref="roles")

    def __init__(self, name, **kwargs):
        """Create instance."""
        super().__init__(name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return f"<Role({self.name})>"


class User(UserMixin, PkModel):
    """A user of the app."""

    __tablename__ = "users"
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.LargeBinary(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        super().__init__(username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return f"{self.first_name} {self.last_name}"

    def __repr__(self):
        """Represent instance as a unique string."""
        return f"<User({self.username!r})>"

congo/checkout/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, validators, StringField, IntegerField


class CheckoutForm(FlaskForm):
    first_name = StringField()
    last_name = StringField()
    address = TextAreaField(u'Mailing Address', [validators.required(), validators.length(max=200)])
    zipcode = IntegerField(u'Zip Code', [validators.required()])
    credit_card_number = IntegerField('Credit Card Number', [validators.required()])
    credit_card_ccv = IntegerField('CCV', [validators.required()])

congo/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(FlaskForm):
    """Register form."""

    username = StringField(
        "Username", validators=[DataRequired(), Length(min=3, max=25)]
    )
    email = StringField(
        "Email", validators=[DataRequired(), Email(), Length(min=6, max=40)]
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=40)]
    )
    confirm = PasswordField(
        "Verify password",
        [DataRequired(), EqualTo("password", message="Passwords must match")],
    )

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

congo/book/views.py
from flask import Blueprint, render_template
from flask_login import login_required

from .forms import SearchForm
from .models import Book

blueprint = Blueprint("book", __name__, url_prefix="/book", static_folder="../static")


@blueprint.route("/<int:book_id>", methods=['GET'])
@login_required
def book_detail(book_id):
    book = Book.get_by_id(book_id)
    if book:
        return render_template("book/book_detail.html", book=book)

congo/checkout/views.py
from flask import Blueprint, jsonify, session, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user

from .forms import CheckoutForm
from .models import Checkout
from ..cart.models import Cart
from ..utils import flash_errors

blueprint = Blueprint("checkout", __name__, url_prefix="/checkout", static_folder="../static")


@blueprint.route("/add_book/<int:book_id>", methods=['POST'])
@login_required
def add_book(book_id):
    """List members."""
    cart_id = session.get("cart_id")
    if cart_id is None:
        cart = Cart.create(
            user_id=current_user.id
        )
        session["cart_id"] = cart.id
    else:
        cart = Cart.get_by_id(cart_id)

    checkout = Checkout.create(
        cart_id=cart.id,
        book_id=book_id,
    )

    return jsonify({"data": {
        "cart_id": cart.id,
        "book_id": book_id,
        "id": checkout.id
    }})


@blueprint.route("/remove_book/<int:checkout_id>", methods=['GET', 'POST'])
@login_required
def remove_book(checkout_id):
    checkout = Checkout.get_by_id(checkout_id)
    checkout.delete()
    flash("You deleted the item.", "success")
    return redirect(url_for('checkout.home'))


@blueprint.route("/", methods=['GET', 'POST'])
def home():
    cart_id = session.get("cart_id")
    if cart_id:
        cart = Cart.get_by_id(cart_id)
        checkouts = cart.checkouts
        total = sum([item.book.price for item in checkouts])
        return render_template("checkout/home.html", checkouts=checkouts, total=total)
    return redirect(url_for('user.home'))


@blueprint.route("/submit", methods=['GET'])
@login_required
def submit():
    cart_id = session.get("cart_id")
    if cart_id:
        cart = Cart.get_by_id(cart_id)
        cart.update(is_submitted=True)
        session.pop("cart_id")
        return render_template("checkout/thank_you.html")
    return redirect(url_for('user.home'))


@blueprint.route("/credit_card", methods=['GET', 'POST'])
@login_required
def credit_card():
    form = CheckoutForm()
    cart_id = session.get("cart_id")
    checkouts=None
    if cart_id:
        cart = Cart.get_by_id(cart_id)
        checkouts = cart.checkouts
    if request.method == "POST" and form.validate_on_submit():
        return redirect(url_for('checkout.submit'))
    flash_errors(form)
    return render_template("checkout/credit_card.html", form=form,  checkouts=checkouts,)

congo/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, jsonify, session, request
from flask_login import login_required

from congo.book.forms import SearchForm
from congo.book.models import Book
from congo.cart.models import Cart
from congo.extensions import login_manager
from congo.user.models import User

blueprint = Blueprint("user", __name__, url_prefix="/user", static_folder="../static")


@login_manager.user_loader
def load_user(user_id):
    """Load user by ID."""
    return User.get_by_id(int(user_id))


@blueprint.route("/")
@login_required
def home():
    """List members."""
    query_string = request.args.get("query_string", None)

    form = SearchForm(query_string=query_string)

    books = form.books
    cart_id = session.get("cart_id")
    checkouts = []
    if cart_id:
        cart = Cart.get_by_id(cart_id)
        checkouts = cart.checkouts
    return render_template("users/home.html", books=books, cart_id=cart_id, checkouts=checkouts)


@blueprint.route("/current_user", methods=["POST"])
@login_required
def current_logged_user():
    """List members."""
    user_id = session.get("user_id", None)
    if user_id:
        return jsonify({
            "data": {
                "id": user_id
            }
        })
    return jsonify({})

congo/templates/users/checkout.html
{% extends "layout.html" %}
{% block content %}

    <div class="mt-3">
            <h1 class="lead display-6 border-bottom">Checkout</h1>
        <div class="">
            <table class="table">
                <thead class="table-light">
                <tr>
                    <td>#</td>
                    <td>Book Name</td>
                    <td>Author</td>
                    <td>ISBN 13</td>
                    <td>Price</td>
                     <td>Action</td>
                </tr>
                </thead>
                <tbody>
                {% for item in checkouts %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ item.book.title }}</td>
                        <td>{{ item.book.author }}</td>
                        <td>{{ item.book.primary_isbn13 }}</td>
                        <td>{{ item.book.price }}</td>
                        <td><a class="btn btn-outline-danger" href="/checkout/remove_book/{{ item.id }}">Delete</a></td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="4">Total</td>
                    <td >{{ total }}</td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>

    </div>
{% endblock %}
{% block page_js %}
{#    <script type="text/javascript">#}
{#        $(".delete").on("click", function (event){#}
{#            const checkout_id = $(this).data("checkoutId");#}
{#             $.ajax({#}
{#                type: "POST",#}
{#                url: "/checkout/remove_book/"+checkout_id,#}
{#                data: {},#}
{#                success: function (data) {#}
{#                    #}
{#                },#}
{#            })#}
{#        })#}
{#    </script>#}
{% endblock %}

congo/templates/users/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="mt-2">
        <h3 class="lead display-6 border-bottom">Best Sellers: </h3>

        <div class="d-flex align-content-between flex-wrap align-items-stretch">
            {% for book in books %}
                <div class="card shadow mx-2 my-3" style="width: 200px">
                    <a href="{{ url_for('book.book_detail', book_id=book.id) }}">
                        <img src="{{ book.book_image_url }}" class="card-img-top" alt="..."
                             onerror="this.onerror=null; this.src='/static/book.svg'">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title small">{{ book.title }}</h5>
                        <p class="card-text small fw-light">{{ book.description[:50] }} ...</p>
                        <p class="card-text text-muted small">Author: {{ book.author }}</p>
                    </div>
                    <div class="card-footer"> ${{ book.price }}
                        <button class="btn btn-outline-primary btn-sm add-cart" data-book-id="{{ book.id }}">
                            <i class="fa fa-cart-plus"></i>
                        </button>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block page_js %}
    <script type="text/javascript">
        let current_user_id = null;
        let cart_id = null;

        function get_or_create_cart() {
            $.ajax({
                type: "POST",
                url: "/cart/get_create",
                data: {},
                success: function (data) {
                    cart_id = data["data"]["id"]
                },
            })

            $.ajax({
                type: "POST",
                url: "{{ url_for('user.current_logged_user') }}",
                data: {},
                success: function (data) {
                    current_user_id = data["data"]["id"]
                },
            })
        }

        get_or_create_cart();
        const add_cart_items = $('#cart-items');

        $(".add-cart").on("click", function () {
            const total_items = parseInt(add_cart_items.text());
            add_cart_items.text(total_items + 1)
            const book_id = $(this).data("bookId");
            $.ajax({
                type: "POST",
                url: "/checkout/add_book/" + book_id,
                data: {},
                success: function (data) {
                    cart_id = data["data"]["id"]
                },
            })
        })
    </script>
{% endblock %}