congo/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template, jsonify, session, request
from flask_login import login_required

from congo.book.forms import SearchForm
from congo.book.models import Book
from congo.cart.models import Cart
from congo.extensions import login_manager
from congo.user.models import User

blueprint = Blueprint("user", __name__, url_prefix="/user", static_folder="../static")


@login_manager.user_loader
def load_user(user_id):
    """Load user by ID."""
    return User.get_by_id(int(user_id))


@blueprint.route("/")
@login_required
def home():
    """List members."""
    query_string = request.args.get("query_string", None)

    form = SearchForm(query_string=query_string)

    books = form.books
    cart_id = session.get("cart_id")
    checkouts = []
    if cart_id:
        cart = Cart.get_by_id(cart_id)
        checkouts = cart.checkouts
    return render_template("users/home.html", books=books, cart_id=cart_id, checkouts=checkouts)


@blueprint.route("/current_user", methods=["POST"])
@login_required
def current_logged_user():
    """List members."""
    user_id = session.get("user_id", None)
    if user_id:
        return jsonify({
            "data": {
                "id": user_id
            }
        })
    return jsonify({})

congo/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="text-center">
            <h1>401</h1>
            <p>You are not authorized to see this page. Please <a href="{{ url_for('public.login') }}">log in</a> or
                <a href="{{ url_for('public.register') }}">create a new account</a>.
            </p>
        </div>
    </div>
{% endblock %}

congo/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>Congo: Bookstore</title>
</head>
<body>
{% include "nav.html" %}
<div class="container-fluid">
    {% block content %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
{% block page_js %}
{% endblock %}
</body>
</html>

congo/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <div class="mt-2">
        <h1 class="lead display-5 border-bottom">Best Sellers</h1>

        <div class="d-flex align-content-between flex-wrap align-items-stretch">
            {% for book in books %}
                <div class="card shadow mx-2 my-3" style="width: 200px">
                    <img src="{{ book.book_image_url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title small">{{ book.title }}</h5>
                        <p class="card-text small fw-light">{{ book.description[:50] }} ...</p>
                        <p class="card-text text-muted small">Author: {{ book.author }}</p>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-outline-primary btn-sm add-cart"><i class="fa fa-cart-plus"></i></button>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock %}

congo/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css"
          integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <title>Congo: Bookstore</title>
    <style>
        table {
            width: 50%;
            counter-reset: row-num -1;
        }

        table tr {
            counter-increment: row-num;
        }

        table tr td:first-child::before {
            content: counter(row-num) ". ";
        }
    </style>
</head>
<body>
{% if current_user.is_authenticated %}
    {% include "nav.html" %}
{% endif %}

<div class="container-fluid">
    <div>
        {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %}
            <div class="row">
                <div class="col-md-12">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            <a class="close" title="Close" href="#" data-dismiss="alert"
                            >&times;</a
                            >
                            {{ message }}
                        </div>
                        <!-- end .alert -->
                    {% endfor %}
                </div>
                <!-- end col-md -->
            </div>
            <!-- end row -->
        {% endif %} {% endwith %}
    </div>
    {% block content %}
    {% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
<script
        src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
        crossorigin="anonymous"></script>
<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";

    $.ajaxSetup({
        beforeSend: function (xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
            }
        }
    });
</script>

{% block page_js %}
    <script>


    </script>
{% endblock %}
</body>
</html>

congo/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="d-flex align-items-center justify-content-center" style="height: 500px">

        <div class="card shadow my-auto">
            <div class="card-body p-5">
                <h4 class="card-title mb-3">Login</h4>
                <form id="loginForm" class="mb-5 form" method="POST" action="" role="form">
                    {{ form.csrf_token }}
                    <div class="form-floating mb-3">
                        {{ form.username(placeholder="name@example.com", class_="form-control") }}
                        {{ form.username.label }}
                    </div>
                    <div class="form-floating mb-3">
                        {{ form.password(placeholder="Password", class_="form-control") }}
                        {{ form.password.label }}
                    </div>
                    <input type="submit" class="btn btn-outline-primary" value="Login" name="submit"/>
                </form>
                <p>Don't have an account?</p>
                <a class="btn btn-primary" href="/register">Register</a>
            </div>
        </div>
    </div>
{% endblock %}

congo/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow" style="height: 75px">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('user.home') }}">Congo</a>

        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {#            <li class="nav-item">#}
            {#                <a class="nav-link" href={{ url_for('user.home') }}>Logged in View</a>#}
            {#            </li>#}
        </ul>


        {% if not current_user.is_admin %}
            <form class="d-flex" method="get">
                <input class="form-control me-2" type="search" placeholder="Search Title or Description Keyword"
                       aria-label="Search" name="query_string" style="width: 350px">
                <button class="btn btn-outline-info" type="submit">Go</button>
            </form>
            <a class="btn btn-outline-success position-relative m-3" href={{ url_for('checkout.home') }}><i
                    class="fas fa-shopping-cart"></i>
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
                      id="cart-items">{{ checkouts|length }}</span>
            </a>
        {% endif %}
        {% if current_user.is_authenticated %}
            <a type="button" class="btn btn-outline-success position-relative " href={{ url_for('public.logout') }}>Logout</a>
        {% endif %}
    </div>
</nav>