congo/checkout/models.py
from congo.database import PkModel, reference_col, relationship


class Checkout(PkModel):
    __tablename__ = "checkout"
    cart_id = reference_col("carts", nullable=True)
    carts = relationship("Cart", backref="checkouts")

    book_id = reference_col("book", nullable=True)
    book = relationship("Book", backref="checkouts")

    def __repr__(self):
        return f"<Checkout(id:{self.id}, user_id:{self.cart_id}, book_id:{self.book_id}>"

congo/checkout/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, validators, StringField, IntegerField


class CheckoutForm(FlaskForm):
    first_name = StringField()
    last_name = StringField()
    address = TextAreaField(u'Mailing Address', [validators.required(), validators.length(max=200)])
    zipcode = IntegerField(u'Zip Code', [validators.required()])
    credit_card_number = IntegerField('Credit Card Number', [validators.required()])
    credit_card_ccv = IntegerField('CCV', [validators.required()])

congo/checkout/views.py
from flask import Blueprint, jsonify, session, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user

from .forms import CheckoutForm
from .models import Checkout
from ..cart.models import Cart
from ..utils import flash_errors

blueprint = Blueprint("checkout", __name__, url_prefix="/checkout", static_folder="../static")


@blueprint.route("/add_book/<int:book_id>", methods=['POST'])
@login_required
def add_book(book_id):
    """List members."""
    cart_id = session.get("cart_id")
    if cart_id is None:
        cart = Cart.create(
            user_id=current_user.id
        )
        session["cart_id"] = cart.id
    else:
        cart = Cart.get_by_id(cart_id)

    checkout = Checkout.create(
        cart_id=cart.id,
        book_id=book_id,
    )

    return jsonify({"data": {
        "cart_id": cart.id,
        "book_id": book_id,
        "id": checkout.id
    }})


@blueprint.route("/remove_book/<int:checkout_id>", methods=['GET', 'POST'])
@login_required
def remove_book(checkout_id):
    checkout = Checkout.get_by_id(checkout_id)
    checkout.delete()
    flash("You deleted the item.", "success")
    return redirect(url_for('checkout.home'))


@blueprint.route("/", methods=['GET', 'POST'])
def home():
    cart_id = session.get("cart_id")
    if cart_id:
        cart = Cart.get_by_id(cart_id)
        checkouts = cart.checkouts
        total = sum([item.book.price for item in checkouts])
        return render_template("checkout/home.html", checkouts=checkouts, total=total)
    return redirect(url_for('user.home'))


@blueprint.route("/submit", methods=['GET'])
@login_required
def submit():
    cart_id = session.get("cart_id")
    if cart_id:
        cart = Cart.get_by_id(cart_id)
        cart.update(is_submitted=True)
        session.pop("cart_id")
        return render_template("checkout/thank_you.html")
    return redirect(url_for('user.home'))


@blueprint.route("/credit_card", methods=['GET', 'POST'])
@login_required
def credit_card():
    form = CheckoutForm()
    cart_id = session.get("cart_id")
    checkouts=None
    if cart_id:
        cart = Cart.get_by_id(cart_id)
        checkouts = cart.checkouts
    if request.method == "POST" and form.validate_on_submit():
        return redirect(url_for('checkout.submit'))
    flash_errors(form)
    return render_template("checkout/credit_card.html", form=form,  checkouts=checkouts,)

congo/templates/checkout/credit_card.html
{% extends "layout.html" %}
{% block content %}

    <div class="mt-3">
        <div class="mt-2">
            <h1 class="lead display-5 border-bottom">Checkout</h1>

        </div>
        <div class="container">
            <form method="post"> {{ form.csrf_token }}
                <div class="mb-3">
                    {{ form.first_name.label }}
                    {{ form.first_name(class="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.last_name.label }}
                    {{ form.last_name(class="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.address.label }}
                    {{ form.address(class="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.zipcode.label }}
                    {{ form.zipcode(class="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.credit_card_number.label }}
                    {{ form.credit_card_number(class="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.credit_card_ccv.label }}
                    {{ form.credit_card_ccv(class="form-control") }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>

    </div>
{% endblock %}

congo/templates/checkout/home.html
{% extends "layout.html" %}
{% block content %}

    <div class="mt-3">
        <h1 class="lead display-6 border-bottom">Checkout</h1>
        <div class="">
            <table class="table">
                <thead class="table-light">
                <tr>
                    <td>#</td>
                    <td>Book Name</td>
                    <td>Author</td>
                    <td>ISBN 13</td>
                    <td>Price</td>
                    <td>Action</td>
                </tr>
                </thead>
                <tbody>
                {% for item in checkouts %}
                    <tr>
                        <td>{{ loop.index }}</td>
                        <td>{{ item.book.title }}</td>
                        <td>{{ item.book.author }}</td>
                        <td>{{ item.book.primary_isbn13 }}</td>
                        <td>{{ "$%.2f"|format(item.book.price) }}</td>
                        <td><a class="btn btn-outline-danger" href="/checkout/remove_book/{{ item.id }}">Delete</a></td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="4">Total</td>
                    <td>{{ "$%.2f"|format(total) }}</td>
                    <td></td>
                </tr>
                </tbody>
            </table>
            <div class="d-flex justify-content-end">
                <a type="button" class="btn btn-outline-success" href="{{ url_for('checkout.credit_card') }}">Proceed</a>
            </div>
        </div>

    </div>
{% endblock %}
{% block page_js %}
{% endblock %}

congo/templates/checkout/thank_you.html
{% extends "layout.html" %}
{% block content %}

    <div class="mt-3">
        <div class="d-flex justify-content-center">
            <h1 class="lead display-6 border-bottom">Thank you</h1>
        </div>
        <div class="d-flex justify-content-center">

            <p>Thank you for submitting your order.</p>
        </div>

    </div>
{% endblock %}
{% block page_js %}
{% endblock %}